spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm02?serverTimezone=UTC
    username: root
    password: 670581
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  redis:
    port: 6379
    host: 127.0.0.1
  messages:
    basename: i18n.login  # 配置国际化文件基础名
  rabbitmq:
    virtual-host: /leyou  #虚拟主机
    port: 5672
    host: 192.168.58.144
    username: leyou
    password: leyou
    publisher-confirm-type: correlated  #必须配置这个才会确认回调
    publisher-returns: true


