spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stus?serverTimezone=UTC
    username: root
    password: 670581
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
